# Ufunc em Numpy
Universal functions (ufunc) são funções em Numpy que alteram o array inteiro.

In [1]:
import numpy as np

In [3]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [20]:
np.log10(arr[arr!=0])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126])

In [15]:
np.log10(arr)

/tmp/ipykernel_9383/2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [21]:
# Funções unárias foram mostradas acima. Podemos ter também funções binárias que recebem dois arrays.
x = np.random.randn(8)
x

array([-0.34780294,  1.99948583, -1.97722176,  0.38431085, -0.3716145 ,
        2.13626594,  2.15847717, -0.04845057])

In [22]:
y = np.random.randn(8)
y

array([-1.03523703,  0.76915593,  0.93082904, -0.54056253,  0.20431174,
        0.10529745, -0.73219951, -0.05266409])

In [24]:
np.maximum(x, y) # Devolve o maior valor na comparação entre x e y

array([-0.34780294,  1.99948583,  0.93082904,  0.38431085,  0.20431174,
        2.13626594,  2.15847717, -0.04845057])

In [33]:
# Apresentando a função divmod embutida do Python
inteiro, resto = divmod(5.5, 1)
print(inteiro, end='\n')
print(resto)

5.0
0.5


In [35]:
# E sua contraparte no Numpy: O modf

arr = np.random.randn(7) *5
arr

array([  8.33214346,  -1.38813255,   6.07866343, -12.44333711,
        -4.96523117,   2.93389625,   4.62930649])

In [36]:
np.modf(arr) # retorna uma tupla de arrays

(array([ 0.33214346, -0.38813255,  0.07866343, -0.44333711, -0.96523117,
         0.93389625,  0.62930649]),
 array([  8.,  -1.,   6., -12.,  -4.,   2.,   4.]))

In [40]:
resto, inteiro = np.modf(arr)

In [41]:
resto

array([ 0.33214346, -0.38813255,  0.07866343, -0.44333711, -0.96523117,
        0.93389625,  0.62930649])

In [42]:
inteiro

array([  8.,  -1.,   6., -12.,  -4.,   2.,   4.])