In [36]:
import numpy as np

# Slicing em array

In [37]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


<p>Para achar um elemento específico do array, basta usar uma notação análoga à de lista</p>

In [38]:
print(a[1, 4])

12


<p>Para copiar uma linha específica, use notação similar à lista mas com a indexação de linha colocada.</p>

In [39]:
linha_1 = a[1, :]
print(linha_1)

[ 8  9 10 11 12 13 14]


Para copiar uma coluna:

In [40]:
coluna_4 = a[:, 4]
print(coluna_4)

[ 5 12]


<p>A leitura de cortes específicos da matrizes também pode ser feita usando os slices de listas para determinadas partes seguindo a seguinte lógica:</p>
<p>[start_index, end_index, step]</p>
Ex:

In [41]:
a[0, 1:-1:2] #Linha 0, começa do elemento com index 1, vai até o 
            # último elemento (index -1) com o passo de 2 em 2 elementos

array([2, 4, 6])

<p>Também é possível cortar um array e alterá-lo atribuindo valores que substituam os da matriz original.</p>

In [42]:
print(f'Antes: \n{a}')


a[1,5] = 20

print(f'Depois: \n{a}')

Antes: 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Depois: 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Além disso, é possível alterar uma linha ou coluna inteira com esse raciocínio de slicing:

In [43]:
a[:, 2] = 89 # selecionando a coluna 2 inteira

print(f'{a}\n')

# Para colocar números específicos basta escrevêlos em notação de 
# lista de acordo com o números de valores do slicing. Ex:


a[:,2] = [35, 42]

print(a)

[[ 1  2 89  4  5  6  7]
 [ 8  9 89 11 12 20 14]]

[[ 1  2 35  4  5  6  7]
 [ 8  9 42 11 12 20 14]]


<p> Para matrizes com três dimensões:</p>
(Tente trabalhar de fora pra dentro sempre)

In [44]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]] ])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<p>Para pegar um elemento específico, primeiro selecionamos o conjunto de "listas" desejado. No exemplo acima são apenas dois conjuntos, com índices 0 e 1.</p>

<p>Depois, indicamos o índices da lista no conjunto e depois o índice do elemento na lista. Ex:</p>

<p>[conjunto, lista, elemento]</p>

Para achar o elemento 4:


In [45]:
b[0, 1, 1]

4

<p>Ademais, os slices funcionam de forma similar aqui.</p>
<p>Digamos que estamos interessados na primeira linha inteira de cada
conjunto:</p>

In [46]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

O replace é feito de forma similar, desde que respeite as dimensões originais.

In [48]:
b[:, 1, :] = [[27, 35], [49, 212]]

print(b)

[[[  1   2]
  [ 27  35]]

 [[  5   6]
  [ 49 212]]]
