# Eixos, transposição de eixos e troca de eixos

In [1]:
import numpy as np

In [2]:
# Transposição de matrizes:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
tr_arr = arr.T
tr_arr

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Eixos e troca de eixos

In [5]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
# Eixo 0:
# Somando todos linhas[0] com linhas[0] de cada subarray dentro de arr
arr.sum(axis=0)

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [10]:
# Eixo 1:
# Soma as colunas de cada subarray dentro de arr.
arr.sum(axis=1)

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26]])

In [11]:
# Eixo 2:
# Soma linhas inteiras de cada um dos quatro subarrays dentro dos subarrays de arr
arr.sum(axis= 2)


array([[ 6, 22],
       [38, 54]])

##### Para matrizes de 3 dimensões:
* Eixo 0: Relaciona as linhas e seus correspondentes no outro subarray;
* Eixo 1: Relacionas as colunas e seus correspondentes no outro subarray;
* Eixo 2: Relaciona os conteúdos de linhas inteiras (retorna um array com a quantidade de elementos igual à quantidade de arrays internos);

### Troca de eixos

In [20]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [24]:
a.transpose((1, 0))

array([[1, 3],
       [2, 4]])

In [26]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [27]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [30]:
arr.transpose((2, 1, 0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])