In [24]:
import numpy as np

# Matemática no Numpy

In [25]:
a = np.array([1,2,3,4])

a+2

array([3, 4, 5, 6])

In [26]:
a-2

array([-1,  0,  1,  2])

In [27]:
a*2

array([2, 4, 6, 8])

In [28]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [29]:
b = [5,6,7,8]

In [30]:
a + b

array([ 6,  8, 10, 12])

In [31]:
a - b

array([-4, -4, -4, -4])

In [32]:
a * b

array([ 5, 12, 21, 32])

In [33]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [34]:
b * a

array([ 5, 12, 21, 32])

In [35]:
b / a

array([5.        , 3.        , 2.33333333, 2.        ])

In [36]:
a ** 2

array([ 1,  4,  9, 16])

In [37]:
a ** b

array([    1,    64,  2187, 65536])

### Seno e cos
<p> Tira o valor associado à função trigonométrica de cada elemento do array e retorna um array com esses valores.</p>

In [38]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Álgebra Linear

In [40]:
a = np.ones((2,3))
print(f'{a}\n')
b = np.full((3,2), 2)
print(f'{b}\n')
c = np.matmul(a, b)
print(f'{c}\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[2 2]
 [2 2]
 [2 2]]

[[6. 6.]
 [6. 6.]]



#### Determinante:

In [41]:
np.linalg.det(c)

0.0

In [42]:
d = np.array([[1,2], [3,4]])

np.linalg.det(d)

-2.0000000000000004

Para outras muitas coisas úteis envolvendo operações álgebra linear:
https://numpy.org/doc/stable/reference/routines.linalg.html

### Estatística

In [43]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)

1

In [44]:
np.max(stats)

6