In [16]:
import numpy as np

# Primeiros passos:

### Criando um array:

In [17]:
a = np.array([1,2,3])
b = np.array([[10,12,15], [12,14,19]])
c = np.array([[[1,2, 8], [3, 4, 9]], [[5, 6, 10], [7, 8, 25]]])

### Dimensões:
<p>Dimensões em arrays se trata do nível de complexidade do conjunto de números. </p>
<p>Digamos, uma lista de números terá apenas uma dimensão.</p>
<p>Uma lista de listas terá duas dimensões.</p>
<p>Uma lista de listas de listas terá três dimensões, e assim sucessivamente...</p>

In [18]:
print(f'''a=
 {a}
 o número de dimensões de a é: {a.ndim}\n''')

print(f'''b=
 {b}
 o número de dimensões de b é: {b.ndim}\n''')

print(f'''c=
 {c}
 o número de dimensões de c é: {c.ndim}\n''')

a=
 [1 2 3]
 o número de dimensões de a é: 1

b=
 [[10 12 15]
 [12 14 19]]
 o número de dimensões de b é: 2

c=
 [[[ 1  2  8]
  [ 3  4  9]]

 [[ 5  6 10]
  [ 7  8 25]]]
 o número de dimensões de c é: 3



### Shape
<p> O shape de um array se trata da sua forma. De forma prática, a função shape retornará uma tupla com a seguinte forma: </p>

<p>1 dimensão: (n° de colunas, ) </p>
<p>2 dimensões: (n° de linhas, n° de colunas)</p>
<p>3 dimensões: (n° de linhas, n° de colunas, n° de elementos por sub array)</p>

In [19]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(2, 2, 3)


Como shape retorna uma tupla, pode servir para mudar a forma de um array como nos exemplos abaixo:

In [20]:
d = np.array([[1, 2, 3, 4], [5,6,7,8]])
print(d)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
d.shape= (1, 8)
print(d)

[[1 2 3 4 5 6 7 8]]


In [23]:
d.shape=(4,2)
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### dtype, itemsize, size, nbytes
<p>dtype retornará o tipo de variável dos elementos no array no terminal;</p>
<p>itemsize retornará um número inteiro que representa a quantidade de bytes ocupado por cada elemento do array na memória do sistema; </p>
<p>size retorna a quantidade de elementos por subarray; </p>
<p>nbytes retorna a quantidade bytes que o array ocupa no sistema.</p>

In [25]:
d.dtype

dtype('int64')

Para especificar o tipo de variável desejada na construção do array:

In [26]:
d = np.array([[1, 2, 3, 4], [5,6,7,8]], dtype= 'int32')
d.dtype

dtype('int32')

In [27]:
memoria_item = d.itemsize

print(memoria_item)

4


In [28]:
qt_elementos = d.size

print(qt_elementos)

8


In [29]:
memoria_array = d.nbytes
print(memoria_array)

32
