In [11]:
import numpy as np

# Extração de dados usando numpy:

In [12]:
data = np.genfromtxt('data.txt', delimiter=',')
print(data)
int_data = data.astype('int32') # 
print('\n', int_data,)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]

 [[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Máscaras booleanas e indexação avançada

In [13]:
int_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [14]:
int_data[int_data>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

<p>O código acima funciona porque o numpy permite indexação usando lista.
Exemplo: Digamos que os elementos desejados do array abaixo sejam os das posições [1, 2, 8]</p>

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [22]:
int_data[:, [1,2,8]] # Todos os elementos nas posições 1, 2, 8 do array

array([[13, 21, 34],
       [42, 12,  6],
       [22, 33, 78]], dtype=int32)

In [27]:
a = np.any(int_data>50, axis=0)
print(a)
a.size

[False False False False  True  True False  True  True False False False
 False False False False  True  True]


18

In [28]:
((int_data> 50) & (int_data <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [39]:
# Exercício final curso numpy:

mt = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])
print(mt[2:4, 0:2], '\n')
print(mt[[0,1,2,3], [1,2,3,4]], '\n')
#print(mt[[0,4,5], 3:5]) ou 
print(mt[[0,4,5], 3:])

[[11 12]
 [16 17]] 

[ 2  8 14 20] 

[[ 4  5]
 [24 25]
 [29 30]]
