In [1]:
import numpy as np

# Reorganização de arrays:

In [2]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Empilhamento vertical de arrays: (vertically stacking vectors)

In [6]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# É possível empilhar sem limitações os vetores:

np.vstack([v1,v2,v1,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### Empilhamento horizontal (horizontal stack)

In [9]:
np.hstack([v1, v2])

array([1, 2, 3, 4, 5, 6, 7, 8])