In [1]:
import numpy as np

# Tipos diferentes de arrays

### Matriz de 0s e 1s:
<p>Por padrão, esse array é constituído de valores 0 em float</p>
OBS: Não esqueça que o primeiro valor da função é uma *tupla*.

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.zeros((2, 3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [4]:
teste = np.ones((4,2, 2, 2)) # Array de 4 dimensões
print(teste)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


### Full e full_like
<p> Preenche o array com um número pré-definido pelo usuário. É da forma:</p>
<p>((tupla_do_shape), número escolhido)</p>

In [5]:
np.full((2,3), 19)

array([[19, 19, 19],
       [19, 19, 19]])

### Matriz de números aleatórios
<p>Preencher usando os números de linhas e colunas, não uma tupla.</p>

In [6]:
np.random.rand(4,3)

array([[0.62218792, 0.90753513, 0.98555721],
       [0.75352228, 0.47955724, 0.36587786],
       [0.49912534, 0.31409206, 0.11000955],
       [0.28384886, 0.2944766 , 0.01097042]])

In [7]:
np.random.randint(1, 17, size=(3,3)) #Início e fim parecidos com for

array([[ 6,  7,  3],
       [ 8,  8, 12],
       [ 1,  4,  2]])

### Matriz identidade:

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Repeat:
Para repetir um array, deve ser usada a função repeat, de preferência em arrays multidimensionais. Ex;

In [9]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0) # Recebe o array e a quantidade de repetições

print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


<p>Desafio dos 31 minutos do vídeo:</p>
https://www.youtube.com/watch?v=QUT1VHiLmmI&t=27s

In [14]:
ext = np.ones((5,5), dtype= 'int32')
ext[1:4, 1:4] = np.zeros((3,3), dtype = 'int32') # Ou
# ext[1:4, 1:4] = 0
# ext[1:-1, 1:-1] = 0
ext[2,2] = 9

print(ext)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
